### ISSUE TITLE
Output aggregation: distinguish spring and fall for frost during snowfree period

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#220]
Overall aggregation option `dailyFrostInSnowfreePeriod` gains two new output variables:
- `TminBelowNegXCwithoutSpringSnowpack_days` = Number of days with surface-tmin < X C without snowpack during Y days after end of longest continuous snowpack
- `TminBelowNegXCwithoutFallSnowpack_days` = Number of days with surface-tmin < X C without snowpack during Y days before start of longest continuous snowpack

All output variables for `dailyFrostInSnowfreePeriod` should use surface temperature and not air temperatures when available.

Where Y is half of the days between end and start of longest continuous snowpack -- so that there is no double counting of frost events, i.e., for each year `TminBelowNegXCwithoutSnowpack_days == TminBelowNegXCwithoutSpringSnowpack_days + TminBelowNegXCwithoutFallSnowpack_days`

**Comment by CaitlinA** [comment]
@Zachary-Kramer Please work on this enhancement

**Comment by Zachary-Kramer** [comment]
I am confused by this. 

`TminBelowNegXCwithoutSpringSnowpack_days` covers from the last day of the longest continuous snowpack until Y days after
`TminBelowNegXCwithoutFallSnowpack_days` covers from Y days before and to the start of the longest continuous snowpack
`TminBelowNegXCwithoutSnowpack_days` covers the entire year (`SWE.dy$val == 0 & temp.dy$min < iTmin`)

How are Fall and Spring supposed to add up to `TminBelowNegXCwithoutSnowpack_days`? Is `TminBelowNegXCwithoutSnowpack_days` supposed to be only before/after the longest continuous snowpack? Or am I misunderstanding the code?

I have laid out an approach to this aggregation ignoring this confusion and have hit some issues due to my lack of understanding of when/how the water year should be used. Specifically, I don't know how we should deal with indices that are outside of the normal year. For instance, the first day of continuous snow could be day 12 of the calendar year, and Y could be 40, so we want to start counting the Spring period on day -28. It seems like this can be done using snow years, because then the aggregation starts 1 year after the first simulation year, which lets us index the previous year, but my approach is knowingly flawed. I have pushed my branch but unfortunately it is not functionally complete. I have added TODO comments, though if my approach is drastically flawed then it might be easier to start over.

I will not have access to a computer until January 5th, so this is as far as I can develop this aggregation.

**Comment by dschlaep** [comment]
`TminBelowNegXCwithoutSnowpack_days` is not an output, new or otherwise. I used this to explain what is requested.

We differentiate between any day with snow (SWE > 0) and days with continuous snowpack (SWE > 0 for a certain number of continuous days).

For instance, 
- Nov 17: first snow fall of the season - snow melts next day ==> SWE > 0, but not part of a continuous snowpack
- Dec 14: snow falls and doesn't melt until March 23 of the following year ==> continuous snowpack
- April 2: late winter snow fall - snow melts within two days ==> SWE > 0, but not part of a continuous snowpack
- Aug 1: crazy summer snow blizzard - snow melts within hours ==> not part of a continous snowpack

Now:
- `TminBelowNegXCwithoutSpringSnowpack_days` = Number of days for which
    - surface-tmin < X C  &
    - SWE = 0 &
    - doy > March 23 (end of continous snowpack) and doy < July 31 (half way between March 23 and Dec 14)

and similarly for:
- `TminBelowNegXCwithoutFallSnowpack_days` = Number of days for which
    - surface-tmin < X C  &
    - SWE = 0 &
    - doy < Dec 14 (start of continous snowpack) and doy >= July 31 (half way between March 23 and Dec 14)

and analogously for the southern hemisphere.

**Comment by dschlaep** [comment]
Maybe we want to name the new outputs
- `TminBelowNegXCwithoutSpringSnow_days` instead of `TminBelowNegXCwithoutSpringSnowpack_days`
- `TminBelowNegXCwithoutFallSnow_days` instead of `TminBelowNegXCwithoutFallSnowpack_days`

**Comment by Zachary-Kramer** [comment]
Okay, so I have this aggregation working seemingly as intended except for one situation, which is when a year has no snow and hence no continuous snow pack. How should we handle this?

For instance, in your example for `TminBelowNegXCwithoutSpringSnowpack_days`, what if instead of the next continuous snow pack being Dec 14th of the following year, but rather of the _year after that_? Do you want to count all the days of the intermediate year? This seems like it would skew the data a lot.
