### ISSUE TITLE
Output aggregation: number of cold days

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSFSW2#221]
Comparable to how `dailyHotDays` counts the number of days with maximum daily temperature  > `Tmax_crit_C`, we need a new output aggregation option `dailyColdDays`.

`TminSurfaceBelowNegXC_days` = number of days with **surface** temperature < `Tmin_crit_C`.

**Comment by CaitlinA** [comment]
@Zachary-Kramer Please work on this enhancement

**Comment by Zachary-Kramer** [comment]
I am a little bit confused, could you clarify something for me? In our `temp.dy` output we have the following columns:

![image](https://user-images.githubusercontent.com/16931318/34071521-ac886ea0-e277-11e7-9213-bdcee33a4422.png)

`dailyHotDays` is using the `max_c` column, but instead of `dailyColdDays` using `min_c` you want it to use the minimum surface temperature, correct? Does this mean we also need to replace `surfaceTemp_C` with `minSurfaceTemp_C`, `maxSurfaceTemp_C` and `avgSurfaceTemp_C`? Or am I misunderstanding something?

**Comment by dschlaep** [comment]
Currently, we only have `surface temperature` -- `SOILWAT2` does not (yet) calculate diurnal range of surface temperature. I adjusted the issue.

**Comment by CaitlinA** [comment]
Implementation merged with master https://github.com/DrylandEcology/rSFSW2/commit/4b3ad1ecc073fd1b53e4b4f4f80472080c51992b
