### ISSUE TITLE
Add column 'Cokey' to input master

### ISSUE THREAD

**Issue by Zachary-Kramer** [DrylandEcology/rSFSW2#283]
Add column "Cokey" to Input Master if SSURGO was used.

Not too much code should be needed for this, it just needs to be placed intelligently. Perhaps a value `cokey` should be added to the variable "MMC" (ExtractData_Soils, first ~30 lines), be modified within the SSURGO main function by grabbing keys[2], and then the function that writes the MMC variable (Misc. Functions.R / update_datasource_masterfield) should be modified to write the cokey.

MMC variable currently:
```
  list(source = sites_soils_source, data = dtemp, idone = vector(),
    use = sw_input_soils_use, input = sw_input_soils, input2 = sw_input_soillayers,
    cn = coln, vars = vars, nvars = nvars, do_include = do_include)
```
Writing directly to Input Master, like what happens to the soil layer and texture CSVs, could also be explored, but I am concerned that the cokey values will be erased when the MMC variable is written.

Suggestions are welcome. Modifying the MMC variable seems a bit excessive because it holds a lot of important data (e.g. soil texture), and the cokey is specific to one extraction, but it is one solution that I see.

@CaitlinA @dschlaep your input is welcomed

**Comment by dschlaep** [comment]
What information does `cokey` convey?

**Comment by Zachary-Kramer** [comment]
It is an integer that indicates which rows / component(?) the SSURGO data was taken from. This column exists in the soil layers CSV, however Caitlin requested that it also be saved in Input Master

**Comment by dschlaep** [comment]
We don't store this level of detail for the other data extractions. Why for SSURGO, why in `input master`?

If you do go ahead, please use a more descriptive name, for instance, at least something like `SSURGO_cokey`.

Why not dump it in a csv or rds file in the `4_Data_SWOutputAggregated/temp` folder? That is where (temporary) climate downscaling information is stored.

What do you plan to do if there are more than one `cokey` for a cell?

**Comment by Zachary-Kramer** [comment]
@CaitlinA this is more of a discussion for you than me.

> What do you plan to do if there are more than one cokey for a cell?

Thankfully there is only 1 `cokey` per extraction, and only 1 extraction per site, so we shouldn't run into this

**Comment by dschlaep** [comment]
> Thankfully there is only 1 cokey per extraction, and only 1 extraction per site, so we shouldn't run into this

--> This is only true if `sim_space[["scorp"]] == "point"`, but not if `sim_space[["scorp"]] == "cell"`. Any wall-to-wall simulation project uses the latter setting, e.g., the ongoing Decadal Project, which once upon a time was supposed to use SSURGO.

**Comment by Zachary-Kramer** [comment]
I was not aware of this. Nevertheless, Caitlin and I already discussed this scenario and there were two solutions we saw:

1. Add a delimiter (e.g. `-`) between cokeys
2. Add multiple columns

But, this new information could provide more reasoning for not storing them in input master. Is there a quick explanation or example of how the `cell` projects extract to the soil CSVs? e.g. does each site end up having multiple rows? The soil layers CSV has `cokey` and `mukey` columns as well, so I want to make sure the logic for writing them will still work with cell projects.

**Comment by dschlaep** [comment]
Have you reviewed code for the existing data extraction functions, e.g., `do_ExtractSoilDataFromISRICWISE_Global`, `do_ExtractSkyDataFromNOAAClimateAtlas_USA`, `do_ExtractElevation_NED_USA` etc., as basis for how to deal with `point`/`cell` extractions?

**Comment by Zachary-Kramer** [comment]
I only used STATSGO as a reference:

```
    if (sim_space[["scorp"]] == "point") {
      cell_res_conus <- NULL
      args_extract <- list(y = sites_conus, type = sim_space[["scorp"]])

    } else if (sim_space[["scorp"]] == "cell") {
      cell_res_conus <- align_with_target_res(res_from = sim_space[["sim_res"]],
        crs_from = sim_space[["sim_crs"]], sp = sim_space[["run_sites"]][todos, ],
        crs_sp = sim_space[["crs_sites"]], crs_to = crs_data)
      args_extract <- list(y = cell_res_conus, coords = sites_conus, method = "block",
        type = sim_space[["scorp"]])
    }
```

```
    temp <- do.call("extract_rSFSW2", args = c(args_extract, x = list(g)))
```
But at the time did not understand the significance of the point/cell options. I cannot immediately see how this impacts the CSVs. I can set up a test project if needed, just wanted to see if there was quick information about it as my time is limited. I wasn't aware that this option is used for all the data extraction functions. I'm assuming this means SSURGO also needs to account for it, yes?

**Comment by dschlaep** [comment]
Yes, we need to be able to use `cell` for SSURGO extractions.

Read up on `?extract_rSFSW2` and `?extract_SFSW2_cells_from_raster`

> But at the time did not understand the significance of the point/cell options.

--> Why not check out the existing code, realize that every/most comparable extraction function implements this and is thus an important functionality, and then ask?

> I cannot immediately see how this impacts the CSVs. 

--> As you can see in the existing code, the structure of `SWRuns_InputData_soils_v12.csv` is not affected because it shouldn't be. However, how the values are calculated differs substantially because the values represent very different things if a simulation project is `point` versus `cell` based. This is all explained in the project description file:
```
#----- Spatial setup of simulations
# scorp := one of c("point", "cell"), whether to interpret the simulation locations
#   provided in 'SWRunInformation' as point locations (1D-sites) or as means of 2D-cells
# If scorp == "cell" then provide either valid path to 'fsimraster' (takes precedence) or
#   (grid resolution and grid crs)
# Currently, implemented for
# - actions[["map_inputs"]]
# - external extractions:
#  - soils: "ExtractSoilDataFromISRICWISEv12_Global",
#     "ExtractSoilDataFromISRICWISE30secV1a_Global",
#     "ExtractSoilDataFromCONUSSOILFromSTATSGO_USA",
#  - elevation: "ExtractElevation_NED_USA", "ExtractElevation_HWSD_Global",
#  - climate normals: "ExtractSkyDataFromNOAAClimateAtlas_USA"
#     NOTE: not implemented for 'ExtractSkyDataFromNCEPCFSR_Global'
```

**Comment by Zachary-Kramer** [comment]
> Why not check out the existing code, realize that every/most comparable extraction function implements this and is thus an important functionality, and then ask?

While developing SSURGO I put the seemingly small functionalities I didn't understand yet on the back-burner, most of which I understood after working with the SSURGO data, but forgot to revisit the point/cell option. It's my mistake and I'm trying to fix it.

I will read `?extract_rSFSW2` and `?extract_SFSW2_cells_from_raster`

**Comment by CaitlinA** [comment]
@dschlaep 

I want to save the cokey in order to be able to backtrack and look at more information than just texture for sites. I used SSURGO data for a SOILWAT2 project, where I extracted the data myself and not through the wrapper, and a frequent question from colloborators was "what component key was the soil type?"

I did originally think that the Input Master would be a good place to save the cokey, but I am open for it to be recorded somewhere else. Why in the /temp folder? Essentially, I don't see this as "temporary" information, but information about input data to the model. Maybe in one of the soils files is better.

In regards to being able to extract data from cells, SSURGO data is stored as a database.

I believe the current SSURGO functionality is taking the inputs coordinates and converting them to (a very small) bounding box, "convert_coords_to_bounding_box", such that only one "mukey" or map unit key, is returned for each set of coordinates. Each mukey potentially has multiple "component keys" associated with it. The cokey with the greatest percent (comppct - "The percentage of the component of the map unit." ) is selected for the site. 

Perhaps for the cell based extraction we can create a bounding box that accounts for the resolution of the simulation and then take a mean of the textures across the selected cokey for all associated mukeys?

**Comment by dschlaep** [comment]
@CaitlinA 

I'm fine with storing that additional information, but I think that appending such metadata to our existing tables is counterproductive speed and memory-wise. I am fine with storing it as an additional file somewhere, what about under `0_Metadata`?

> Each mukey potentially has multiple "component keys" associated with it. 

--> That is normal for soil data. See how the existing functions are handling it.

> Perhaps for the cell based extraction we can create a bounding box that accounts for the resolution of the simulation and then take a mean of the textures across the selected cokey for all associated mukeys?

--> The package has fully implemented and optimized functionality to perform all of such operations (btw, it shouldn't be the mean, the area-weighted mean is the appropriate metric). The SSURGO extraction code simply needs to connect to what is already there as all the other extraction functions are already doing.

**Comment by Zachary-Kramer** [comment]
Two new issues have been created based off this discussion: #288 and #287 

This issue is no longer needed.
